version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8090:8000"
    environment:
      - ADMIN_TOKEN=thermal_sim_admin_2024_secure_token
    volumes:
      - ./backend/models:/app/models
      - ./backend/results:/app/results
      - ./backend/data:/app/data
    networks:
      - thermal-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3010:80"
    depends_on:
      - backend
    networks:
      - thermal-network

networks:
  thermal-network:
    driver: bridge

volumes:
  models:
  results:
  data: